
export {Home} from './Home/Home'
export {LogIn} from './Login/LogIn'
export {Result} from './Result/Result'
export {Detail} from './Detail/Detail'
export {Cart} from './Cart/Cart'
export {Dashboard} from './Dashboard/Dashboard'
export {Buy} from './Buy/Buy'
export {Categories} from './Categories/Categories'
export {Orders} from './Orders/Orders'
export {Payment} from './payment/Payment'
export {ProductInfo} from './Product/ProductInfo'
export {Stack} from './Stack/Stack'
export {SubCategories} from './subCategories/subCategories'